apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yelb-secure
  name: redis-server
spec:
  selector:
    matchLabels:
      app: redis-server
      tier: cache
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
        tier: cache
    spec:
      initContainers:
      - image: curlimages/curl:latest
        imagePullPolicy: Always
        name: sidecar
        env:
        - name: version
          value: 5.0.20261
        - name: username
          valueFrom:
            secretKeyRef:
              name: aqua
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: aqua
              key: password
        command: ["/bin/sh", "-c" ,"curl --user $(username):$(password) https://download.aquasec.com/micro-enforcer/$(version)/microenforcer > /test/microenforcer && chmod +x /test/microenforcer" ]
        volumeMounts:
        - name: sidecar
          mountPath: /test
      containers:
        - name: redis-server
          image: redis:4.0.2
          env:
          - name: AQUA_SERVER
            value: "{{ .Values.env }}"
          - name: AQUA_TOKEN
            value: fargate
          ports:
            - containerPort: 6379
          command: ["/test/microenforcer", "docker-entrypoint.sh","redis-server"]
          volumeMounts:
            - mountPath: /test
              name: sidecar
      volumes:
      - name: sidecar
        emptyDir: {}